import type {MathConstants} from "@math-blocks/opentype";

export const constants: MathConstants = {
    scriptPercentScaleDown: 70,
    scriptScriptPercentScaleDown: 55,
    delimitedSubFormulaMinHeight: 1325,
    displayOperatorMinHeight: 1800,
    mathLeading: {value: 150, deviceOffset: 0},
    axisHeight: {value: 258, deviceOffset: 0},
    accentBaseHeight: {value: 480, deviceOffset: 0},
    flattenedAccentBaseHeight: {value: 656, deviceOffset: 0},
    subscriptShiftDown: {value: 210, deviceOffset: 0},
    subscriptTopMax: {value: 368, deviceOffset: 0},
    subscriptBaselineDropMin: {value: 160, deviceOffset: 0},
    superscriptShiftUp: {value: 360, deviceOffset: 0},
    superscriptShiftUpCramped: {value: 252, deviceOffset: 0},
    superscriptBottomMin: {value: 120, deviceOffset: 0},
    superscriptBaselineDropMax: {value: 230, deviceOffset: 0},
    subSuperscriptGapMin: {value: 150, deviceOffset: 0},
    superscriptBottomMaxWithSubscript: {value: 380, deviceOffset: 0},
    spaceAfterScript: {value: 40, deviceOffset: 0},
    upperLimitGapMin: {value: 135, deviceOffset: 0},
    upperLimitBaselineRiseMin: {value: 300, deviceOffset: 0},
    lowerLimitGapMin: {value: 135, deviceOffset: 0},
    lowerLimitBaselineDropMin: {value: 670, deviceOffset: 0},
    stackTopShiftUp: {value: 470, deviceOffset: 0},
    stackTopDisplayStyleShiftUp: {value: 780, deviceOffset: 0},
    stackBottomShiftDown: {value: 385, deviceOffset: 0},
    stackBottomDisplayStyleShiftDown: {value: 690, deviceOffset: 0},
    stackGapMin: {value: 150, deviceOffset: 0},
    stackDisplayStyleGapMin: {value: 300, deviceOffset: 0},
    stretchStackTopShiftUp: {value: 800, deviceOffset: 0},
    stretchStackBottomShiftDown: {value: 590, deviceOffset: 0},
    stretchStackGapAboveMin: {value: 68, deviceOffset: 0},
    stretchStackGapBelowMin: {value: 68, deviceOffset: 0},
    fractionNumeratorShiftUp: {value: 585, deviceOffset: 0},
    fractionNumeratorDisplayStyleShiftUp: {value: 640, deviceOffset: 0},
    fractionDenominatorShiftDown: {value: 585, deviceOffset: 0},
    fractionDenominatorDisplayStyleShiftDown: {value: 640, deviceOffset: 0},
    fractionNumeratorGapMin: {value: 68, deviceOffset: 0},
    fractionNumDisplayStyleGapMin: {value: 150, deviceOffset: 0},
    fractionRuleThickness: {value: 68, deviceOffset: 0},
    fractionDenominatorGapMin: {value: 68, deviceOffset: 0},
    fractionDenomDisplayStyleGapMin: {value: 150, deviceOffset: 0},
    skewedFractionHorizontalGap: {value: 350, deviceOffset: 0},
    skewedFractionVerticalGap: {value: 68, deviceOffset: 0},
    overbarVerticalGap: {value: 175, deviceOffset: 0},
    overbarRuleThickness: {value: 68, deviceOffset: 0},
    overbarExtraAscender: {value: 68, deviceOffset: 0},
    underbarVerticalGap: {value: 175, deviceOffset: 0},
    underbarRuleThickness: {value: 68, deviceOffset: 0},
    underbarExtraDescender: {value: 68, deviceOffset: 0},
    radicalVerticalGap: {value: 85, deviceOffset: 0},
    radicalDisplayStyleVerticalGap: {value: 170, deviceOffset: 0},
    radicalRuleThickness: {value: 68, deviceOffset: 0},
    radicalExtraAscender: {value: 78, deviceOffset: 0},
    radicalKernBeforeDegree: {value: 65, deviceOffset: 0},
    radicalKernAfterDegree: {value: -335, deviceOffset: 0},
    radicalDegreeBottomRaisePercent: 55,
};
