/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Node = NumericNode | LogicNode | SetNode;
export type NumericNode =
    | Num
    | Infinity
    | Pi
    | Ident
    | Ellipsis
    | Add
    | Mul
    | Func
    | Div
    | Mod
    | Root
    | Pow
    | Log
    | Neg
    | Abs
    | Sum
    | Prod
    | Limit
    | Diff
    | PDiff
    | Int;
export type Num = Common & {
    type: "number";
    value: string;
    [k: string]: unknown;
};
export type Infinity = Common & {
    type: "infinity";
    [k: string]: unknown;
};
export type Pi = Common & {
    type: "pi";
    [k: string]: unknown;
};
export type Ident = Common & {
    type: "identifier";
    name: string;
    subscript?: Node;
    [k: string]: unknown;
};
export type Ellipsis = Common & {
    type: "ellipsis";
    [k: string]: unknown;
};
export type Add = Common & {
    type: "add";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type Mul = Common & {
    type: "mul";
    args: [Node, Node, ...Node[]];
    implicit: boolean;
    [k: string]: unknown;
};
export type Func = Common & {
    type: "func";
    func: Node;
    args: Node[];
    [k: string]: unknown;
};
export type Div = Common & {
    type: "div";
    args: [Node, Node];
    [k: string]: unknown;
};
export type Mod = Common & {
    type: "mod";
    args: [Node, Node];
    [k: string]: unknown;
};
export type Root = Common & {
    type: "root";
    radicand: Node;
    index: Node;
    [k: string]: unknown;
};
export type Pow = Common & {
    type: "pow";
    base: Node;
    exp: Node;
    [k: string]: unknown;
};
export type Log = Common & {
    type: "log";
    base: Node;
    arg: Node;
    [k: string]: unknown;
};
export type Neg = Common & {
    type: "neg";
    arg: Node;
    subtraction: boolean;
    [k: string]: unknown;
};
export type Abs = Common & {
    type: "abs";
    arg: Node;
    [k: string]: unknown;
};
export type Sum = Common & {
    type: "sum";
    arg: Node;
    bvar: Ident;
    limits: Limits;
    [k: string]: unknown;
};
export type Limits = Common & {
    type: "limits";
    args: [Node, Node];
    [k: string]: unknown;
};
export type Prod = Common & {
    type: "prod";
    arg: Node;
    bvar: Ident;
    limits: Limits;
    [k: string]: unknown;
};
export type Limit = Common & {
    type: "lim";
    arg: Node;
    bvar: Ident;
    target: Node;
    [k: string]: unknown;
};
export type Diff = Common & {
    type: "diff";
    arg: Node;
    [k: string]: unknown;
};
export type PDiff = Common & {
    type: "pdiff";
    args: [Node, Node];
    [k: string]: unknown;
};
export type Int = Common & {
    type: "int";
    arg: Node;
    bvar: Ident;
    limits: Ident;
    [k: string]: unknown;
};
export type LogicNode =
    | Ident
    | True
    | False
    | And
    | Or
    | Not
    | Xor
    | Implies
    | Iff
    | Eq
    | Neq
    | Lt
    | Lte
    | Gt
    | Gte
    | In
    | NotIn
    | Subset
    | ProperSubset
    | NotSubset
    | NotProperSubset;
export type True = Common & {
    type: "true";
    [k: string]: unknown;
};
export type False = Common & {
    type: "false";
    [k: string]: unknown;
};
export type And = Common & {
    type: "and";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type Or = Common & {
    type: "or";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type Not = Common & {
    type: "not";
    arg: Node;
    [k: string]: unknown;
};
export type Xor = Common & {
    type: "xor";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type Implies = Common & {
    type: "implies";
    args: [Node, Node];
    [k: string]: unknown;
};
export type Iff = Common & {
    type: "iff";
    args: [Node, Node];
    [k: string]: unknown;
};
export type Eq = Common & {
    type: "eq";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type Neq = Common & {
    type: "neq";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type Lt = Common & {
    type: "lt";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type Lte = Common & {
    type: "lte";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type Gt = Common & {
    type: "gt";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type Gte = Common & {
    type: "gte";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type In = Common & {
    type: "in";
    element: Node;
    set: Node;
    [k: string]: unknown;
};
export type NotIn = Common & {
    type: "notin";
    element: Node;
    set: Node;
    [k: string]: unknown;
};
export type Subset = Common & {
    type: "subset";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type ProperSubset = Common & {
    type: "prsubset";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type NotSubset = Common & {
    type: "notsubset";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type NotProperSubset = Common & {
    type: "notprsubset";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type SetNode =
    | Ident
    | Set
    | EmptySet
    | Union
    | Intersection
    | SetDiff
    | CartesianProduct
    | Naturals
    | Integers
    | Rationals
    | Reals
    | Complexes;
export type Set = Common & {
    type: "set";
    args: Node[];
    [k: string]: unknown;
};
export type EmptySet = Common & {
    type: "empty";
    [k: string]: unknown;
};
export type Union = Common & {
    type: "union";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type Intersection = Common & {
    type: "intersection";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type SetDiff = Common & {
    type: "setdiff";
    args: [Node, Node];
    [k: string]: unknown;
};
export type CartesianProduct = Common & {
    type: "cartesian_product";
    args: [Node, Node, ...Node[]];
    [k: string]: unknown;
};
export type Naturals = Common & {
    type: "naturals";
    [k: string]: unknown;
};
export type Integers = Common & {
    type: "integers";
    [k: string]: unknown;
};
export type Rationals = Common & {
    type: "rationals";
    [k: string]: unknown;
};
export type Reals = Common & {
    type: "reals";
    [k: string]: unknown;
};
export type Complexes = Common & {
    type: "complexes";
    [k: string]: unknown;
};

export interface Common {
    id: number;
    loc?: Location;
    [k: string]: unknown;
}
export interface Location {
    path: number[];
    start: number;
    end: number;
    [k: string]: unknown;
}
