const fs = require('fs');

const input = fs.readFileSync('packages/semantic/src/types.ts', {
  encoding: 'utf-8',
});

const output =
  `
/**
 * This file is auto-generated by tools/build-types.js.  To make changes, edit
 * packages/semantic/src/types.ts and then run tools/build-types.js.
 */
 
` +
  input
    .split('\n')
    .map((line, index) => {
      if (
        line.startsWith('export type Node =') ||
        line.startsWith('export type NumericNode =') ||
        line.startsWith('export type LogicNode =') ||
        line.startsWith('export type SetNode =')
      ) {
        return line;
      } else {
        return line
          .replace(/NumericNode/g, 'Node')
          .replace(/LogicNode/g, 'Node')
          .replace(/SetNode/g, 'Node');
      }
    })
    .join('\n');

fs.writeFileSync('packages/parser/src/types.ts', output);
